### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by lpratalimaffei**
@snelliott @avcopan I edited the functional groups and added many more.
You might find some differences in species classification for alkane/alkene/alkynes since I am filtering out some groups. Another change is that the alcohol group is now only identified by the OH atoms (before it was identified by the COH atoms). automol tests calling these functions work

### CODE REVIEW

**Comment by avcopan** [comment]
Sounds great, @lpratalimaffei! Could you fix the linting errors before merging?

You can test them locally by running `./old-lint.sh` ("old" because I am working on a faster linting process, but it doesn't yet cover the whole code).

**Comment by lpratalimaffei** [comment]
Sorry, where should I run this?

Da: avcopan ***@***.***>
Data: venerdì, 11 ottobre 2024 alle ore 18:08
A: Auto-Mech/autochem ***@***.***>
Cc: Luna Pratali Maffei ***@***.***>, Mention ***@***.***>
Oggetto: Re: [Auto-Mech/autochem] Dev (PR #573)

Sounds great, @lpratalimaffei<https://github.com/lpratalimaffei>! Could you fix the linting errors before merging?

You can test them locally by running ./old-lint.sh ("old" because I am working on a faster linting process, but it doesn't yet cover the whole code).

**Comment by avcopan** [comment]
@lpratalimaffei in the AutoChem repo (you can do `pixi run ./old-lint.sh` if you don't have the environment activated).

**Comment by lpratalimaffei** [comment]
the one failed test is from test_rings, maybe @andrydella should check it? my code doesn't affect the functions called in test__cremerpople

**Pull request merged**
